### ISSUE TITLE
Error when starting iamb

### ISSUE THREAD

**Issue by shrit** [ulyssa/iamb#124]
Hi,

I just installed Iamb on arch linux and I am getting this error when starting the software

```
thread 'main' panicked at 'no dirs.downloads value configured!', src/config.rs:336:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Any known cause of this issue?

**Comment by ulyssa** [comment]
This is because it can't find a downloads directory based on the environment variables you have set. On Arch, you can set up the [XDG user directories](https://wiki.archlinux.org/title/XDG_user_directories) to make sure they are present and you have the variables set for you.

If you don't want to do that, you can also either set the `XDG_DOWNLOAD_DIR` environment variable or  [set a `"downloads"` value](https://iamb.chat/configure.html#directories) in  a `"dirs"` object in your `config.json` to indicate where downloads should go.

**Comment by shrit** [comment]
I am still facing the same issue even after I have setup XDG directory, I have also tried to set what you proposed in the configs.json file and it still the same issue

**Comment by shrit** [comment]
@ulyssa any thoughts?

**Comment by ulyssa** [comment]
@shrit Can you share what you put in your `config.json`? I would have expected  the `dirs.downloads` error.
