### ISSUE TITLE
Is there a way to logout

### ISSUE THREAD

**Issue by nightshade427** [ulyssa/iamb#162]
Is there a way to logout

**Comment by aadityadhruv** [comment]
I don't see this in the code, if @ulyssa doesn't mind I can try adding that. I am already currently working on it.

**Comment by ulyssa** [comment]
There's not currently a way to logout, but I would love to see a PR for it!

@aadityadhruv If you haven't seen the [PromptYesNo](https://docs.rs/modalkit/0.0.16/modalkit/input/dialog/struct.PromptYesNo.html) struct, I think that that'd be the way to approach this. (And maybe also require typing the user ID so that the user makes sure they're logging out of the right profile? Something like `:logout user@example.com`)

**Comment by aadityadhruv** [comment]
This sounds good to me! I'll try to work on this over the week. Just a question - I am a bit confused about how `modalkit` works here. Specifically, what does `ApplicationInfo` do? I see it has been `impl` for `IambInfo` but I am not sure what is the purpose of `ApplicationInfo`, since the docs didn't mention a lot.

**Comment by ulyssa** [comment]
The [`ApplicationInfo`](https://docs.rs/modalkit/0.0.16/modalkit/editing/application/trait.ApplicationInfo.html) trait gathers together all of the application-specific types for modalkit, so that only one type (`IambInfo`) is needed instead of several. For example, the [`Window`](https://docs.rs/modalkit/0.0.16/modalkit/widgets/trait.Window.html) trait needs access to the [`ApplicationWindowId`](https://docs.rs/modalkit/0.0.16/modalkit/editing/application/trait.ApplicationWindowId.html) implementation, and it uses `Store` and `UIResult`, which need access to the [`ApplicationStore`](https://docs.rs/modalkit/0.0.16/modalkit/editing/application/trait.ApplicationStore.html) and [`ApplicationError`](https://docs.rs/modalkit/0.0.16/modalkit/editing/application/trait.ApplicationError.html) implementations respectively. Rather than having to have 3+ parameters on `Window`, it just has one which contains everything iamb-specific.

**Comment by aadityadhruv** [comment]
Ah I see, thanks for the info!

**Comment by aadityadhruv** [comment]
@ulyssa I've got a very basic logout working (I think), and I'm planning on adding the Prompt next. I had a question about how to structure it - should the prompt "action" be separate from the actual logout "action"? Also, once the user logs out, should the application be closed, since technically post logout nothing should be accessible?

**Comment by aadityadhruv** [comment]
@ulyssa What do you think of shutting down the application once the user logs out?

**Comment by ulyssa** [comment]
@aadityadhruv That sounds good! There's not anything useful that can be done once logged out, so that makes sense.

**Comment by aadityadhruv** [comment]
@ulyssa How should I go about closing the application? I can either just `exit` right after the Logout action, or I can try to replicate the `WindowAction::Close` which occurs when the user types in `:q`. I tried doing the latter, but I'm having some difficulties in creating the WindowAction to do so.

**Comment by ulyssa** [comment]
This can probably be made a `HomeserverAction::Logout(bool)` variant (where the `bool` indicates whether `!` was used with the command, and can control whether to generate a prompt). When `HomeserverAction` values are executed in `Application::homeserver_command`, you can return a `Vec` of more actions to run.

You can generate a `TabAction::Close(TabTarget::All, CloseFlags::QUIT | CloseFlags::FORCE)` there that gets run after you do the actual logout logic. (You'll want to use `TabAction::Close` over `WindowAction::Close` to make sure you close all windows and tabs, and not just the current one).

**Comment by aadityadhruv** [comment]
Thanks! The latest commit should add all the things you mentioned.

**Comment by ulyssa** [comment]
Pushed as 3b86be0545b7b70a8c5c325b883f82a254b173ec. Thank you for implementing this, @aadityadhruv !
