### ISSUE TITLE
config.json -> config.toml

### ISSUE THREAD

**Issue by aw-bib** [ulyssa/iamb#248]
Only documentary.

The welcome screen of the docs still refers to `config.json` while the [docs](https://iamb.chat/configure.html) only talk about `toml`.

BTW: if it is _easy_ it may be convenient for the welcome screen to actually expand `$CONFIG_DIR`. I got a bit confused as the profiles seem to be moved to `.local/share/iamb` while there is an older `profiles` in `.config/iamb` as well. So at first I was unsure where to put it, as `$CONFIG_DIR` is no variable on Linux.

isRelatedTo: #229

**Comment by ulyssa** [comment]
Expanding `$CONFIG_DIR` is a little difficult due to how `welcome.md` is currently read in, but I have thought about overhauling the Welcome window at some point to make it more interactive than a read-only text window. When I do that, I can take a look at showing the actualy location. For now, I've just put `~/.config/iamb/config.toml` in there as an example for XDG environments.
