### ISSUE TITLE
Self signet certificate

### ISSUE THREAD

**Issue by RazerStvH** [ulyssa/iamb#290]
Can't login to my server using self signed certificate. Even if this certificate trusted for my OS. Even if i used my own root CA. 

If i using just self signet certificate, i have this: "error trying to connect: invalid peer certificate: Other(CaUsedAsEndEntity)"
If i using my own root CA, i have this: "error trying to connect: invalid peer certificate: UnknownIssuer"

Anyway my server work well with android SchildiChat/Element, and with matrix-commander. But also doesn't  work with Element/SchildiChat on windows and linux.

OS: Arch Linux

**Comment by mordquist** [comment]
As iamb uses `rustls` by default, it does not use the system trust store. What happens if you build iamb with native TLS as described [here](https://github.com/ulyssa/iamb/blob/c6982c97372850c62126210b9180726b54e529c1/?PACKAGING.md#linking-against-system-packages)?

I'm curious, any particular reason for not using a "proper" certificate from Let's Encrypt or similar?

**Comment by RazerStvH** [comment]
It does. I want to see notification every time when i sing in. I can see fingerprint of my certificate. And i like to do it manualy.

**Comment by RazerStvH** [comment]
And by the way, I found a solution for Element and SchildiChat. You need to specify --ignore-certificate-errors at startup. Maybe it will help someone. I initially contacted iamb in order to check if it would work. But as it turns out, it also uses its own certificate store.

**Comment by RazerStvH** [comment]
I needed a small private server, no more. I don't need the Federation. 

The problem was that I couldn't log in to the server from the PC. At the same time, I could log in from android.  But I have already found a solution. 

I understand that it does not make sense to issue certificates on my own, but I do not need a valid certificate, due to the lack of federation.

**Comment by K-MeLeOn** [comment]
Some additional information @mordquist, I'm in the same situation as @RazerStvH, but because I want TLS for my local network AND my public one like this :

Client -> public TLS [VPS] -> wireguard to my home network -> private DNS + private pki -> reverse proxy -> local ressources

Each clients in my network trust the custom CA and it can serve external DNS too (public.domain.tld + private.domain.internal).

I'll try some tricks, if it works I'll share it with pleasure :)

### EDIT:

`native-tls` works, here the flake version for nix :

``` nix
{
  description = "iamb with native-tls (uses system trust store)";

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
    iamb-src = {
      url = "github:ulyssa/iamb";
      flake = false;
    };
  };

  outputs = { self, nixpkgs, iamb-src, ... }:
  let
    eachSystem = nixpkgs.lib.genAttrs [
      "x86_64-linux"
      "aarch64-linux"
    ];
  in {
    packages = eachSystem (system:
      let
        pkgs = import nixpkgs {
          inherit system;
        };
      in {
        default = pkgs.rustPlatform.buildRustPackage {
          pname = "iamb";
          version = "native-tls";
          src = iamb-src;

          cargoLock.lockFile = "${iamb-src}/Cargo.lock";
          # Remove the default features `rustls-tls` & `bundled`
          buildNoDefaultFeatures = true;
          # - native-tls : OpenSSL -> system PKI
          # - desktop    : notify-rust
          buildFeatures = [
            "native-tls"
            "desktop"
          ];

          nativeBuildInputs = with pkgs; [
            pkg-config
          ];
          # OpenSSL for native-tls + SQLite (because `bundled-sqlite` is in features.bundled with `rustls-tls`)
          # and because embeded tools isn't the nix way
          buildInputs = with pkgs; [
            openssl
            sqlite
          ] ++ pkgs.lib.optionals pkgs.stdenv.isDarwin (with pkgs.darwin.apple_sdk.frameworks; [
            Security AppKit
          ]);

          doCheck = false;
        };
      });
  };
}
```
