### ISSUE TITLE
Links should be "openable"

### ISSUE THREAD

**Issue by benjajaja** [ulyssa/iamb#43]
Most links are longer than the chat-message-grid-column, and thus are broken up into the next line. Then, they cannot be opened by clicking (most modern terminals have such a feature), nor can they be selected easily for copying and pasting.

If a message has no attachments and `:open` is used, then do a simple match for `^http(s)?://.+` or something like that, and pass a match to the `open` crate, it should open the browser.

**Comment by ptman** [comment]
weechat has raw-mode (M-L), which is quite handy for links

**Comment by benjajaja** [comment]
@ptman what does that do? Something like just printing raw chat lines?

**Comment by ulyssa** [comment]
Implemented in df3148b. I made it so that `<a>` tags get a `[0]`, `[1]`, etc. shown after them, so that it's clear when someone's used markdown to link to something, and I've made it so that running `:open` will open a prompt showing the URLs and asking which number (or letter if you have enough links) you want to open.

If the message is plaintext only, then `:open` will try to parse the message body to see if it's just a URL. There might be room for improvement here, but I imagine that this should be a good step forward for now.
