### ISSUE TITLE
error: failed to select a version for the requirement `clap = "^4.0"`

### ISSUE THREAD

**Issue by BeanieBarrow** [ulyssa/iamb#85]
I got this error while trying to build iamb from source and updating the crates.io index:

```
$ cargo build --release
Updating crates.io index
error: failed to select a version for the requirement `clap = "^4.0"`
candidate versions found which didn't match: 3.2.23, 3.2.22, 3.2.21, ...
location searched: crates.io index
required by package `iamb v0.0.7 (/path/to/iamb)`
```

I'm running Pop!_OS 20.04 with cargo version 1.58.0

I tried editing `cargo.toml` and rewrote the `clap = {version = "4.0", features = ["derive"]}` line to `clap = {version = "3.2.23", features = ["derive"]}`, but that just gave a similar error to the `matrix-sdk` dependency. How can I install this program now?

**Comment by ulyssa** [comment]
You'll need at least Rust 1.66 to build from source, since I'm using some recently stabliized features of the standard library. You can use [`rustup`](https://rustup.rs/) to get a more recent, stable Rust release, or you can download a statically linked Linux binary from the [v0.0.7 release page](https://github.com/ulyssa/iamb/releases/tag/v0.0.7).
